import { NestContainer } from './injector/container';
import { INestApplication, INestMicroservice } from '@nestjs/common';
import { MicroserviceConfiguration } from '@nestjs/microservices';
import { WebSocketAdapter, ExceptionFilter, PipeTransform, NestInterceptor, CanActivate } from '@nestjs/common';
export declare class NestApplication implements INestApplication {
    private readonly container;
    private readonly express;
    private readonly config;
    private readonly logger;
    private readonly routesResolver;
    private readonly microservices;
    private isInitialized;
    private server;
    constructor(container: NestContainer, express: any);
    setupModules(): Promise<void>;
    init(): Promise<void>;
    setupRouter(): Promise<void>;
    connectMicroservice(config: MicroserviceConfiguration): INestMicroservice;
    getMicroservices(): INestMicroservice[];
    startAllMicroservices(callback?: () => void): void;
    startAllMicroservicesAsync(): Promise<void>;
    use(requestHandler: any): void;
    listen(port: number, callback?: () => void): any;
    listen(port: number, hostname: string, callback?: () => void): any;
    listenAsync(port: number, hostname?: string): Promise<any>;
    close(): void;
    setGlobalPrefix(prefix: string): void;
    useWebSocketAdapter(adapter: WebSocketAdapter): void;
    useGlobalFilters(...filters: ExceptionFilter[]): void;
    useGlobalPipes(...pipes: PipeTransform<any>[]): void;
    useGlobalInterceptors(...interceptors: NestInterceptor[]): void;
    useGlobalGuards(...guards: CanActivate[]): void;
    private setupMiddlewares(instance);
    private listenToPromise(microservice);
    private callInitHook();
    private callModuleInitHook(module);
    private hasOnModuleInitHook(instance);
    private callDestroyHook();
    private callModuleDestroyHook(module);
    private hasOnModuleDestroyHook(instance);
}
